Implementación con 93% de cobertura
jgutierrez9891/MISW-Proyecto-Final-II-Back pull request #19
Opened 2023-10-26 03:32 UTC by JEnriqueS

Se agrega ping a servicio de autenticación

2023-10-26 03:46 UTC, CharlyMoraUA requested changes
pendiente agregar variable de jwt en deploy de gcp

2023-10-26 03:48 UTC, jgutierrez9891 requested changes
Falta agregar el secreto de JWT en el pipeline de despliegue ( línea 348)

2023-10-26 12:48 UTC, JEnriqueS commented
Gracias por la observación. Lo he hecho en el último commit

2023-10-27 02:55 UTC, jgutierrez9891 approved these changes
Conforme

2023-10-27 02:56 UTC, merged